name: hydro-bench
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pygeoogc=0.10.1
  - pygeoutils=0.10.1
  - py3dep=0.10.1
  - pynhd=0.10.1
  - pygeohydro=0.10.2
  - pydaymet=0.10.2
  - xarray=0.17.0
  - tqdm
  - sphinx