"""
Author: Wenyu Ouyang
Date: 2022-09-05 23:20:24
LastEditTime: 2025-11-06 15:37:45
LastEditors: Wenyu Ouyang
Description: set file dir
FilePath: \hydrodataset\hydrodataset\__init__.py
Copyright (c) 2021-2022 Wenyu Ouyang. All rights reserved.
"""

__author__ = """Wenyu Ouyang"""
__email__ = "wenyuouyang@outlook.com"

# Import version from _version.py (auto-generated by hatch-vcs)
try:
    from ._version import __version__, __version_tuple__
except ImportError:
    # Fallback version if _version.py doesn't exist yet
    __version__ = "0.0.0+unknown"
    __version_tuple__ = (0, 0, 0, "unknown")

# Re-export config APIs for convenience
from hydrodataset.configs.settings import (
    load_settings,
    get_local_root,
    get_cache_dir,
    DEFAULT_SETTING_PATH,
)
from hydrodataset.configs.data_resolver import (
    READER_ALIASES,
    resolve_data_path,
    DatasetResolutionError,
)

# set some constants for datasets
DATASETS = ["CAMELS", "Caravan", "GRDC", "HYSETS", "LamaH", "MOPEX"]
CAMELS_REGIONS = ["AUS", "BR", "CL", "GB", "US"]
LAMAH_REGIONS = ["CE"]
# For CANOPEX, We don't treat it as a dataset, but a special case for MOPEX. We only have CANOPEX now.
MOPEX_REGIONS = ["CA"]
REGIONS = CAMELS_REGIONS + LAMAH_REGIONS + MOPEX_REGIONS
from .hydro_dataset import *
#from .camelsh_kr import *
#from .lamah_ce import *
#from .camels_us import *
#from .camels import *
